---
development:
  # Change this URL with the URL of the queue you've created
  QUEUE_URL: https://sqs.us-east-1.amazonaws.com/503315808870/soa_queue.fifo
  AWS_ACCESS_KEY_ID: <aws credentials>
  AWS_SECRET_ACCESS_KEY: <aws credentials>
  AWS_REGION: us-east-1
